version: '3.3'

services:
  mysql:
    image: mysql:8
    container_name: mysql8
    environment:
      MYSQL_DATABASE: imdmarket
      MYSQL_USER: imd
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"